spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ASSEMBLEIA
    password: dsv
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  compression:
    enabled: true
  port: ${SERVER_PORT:9082}
  servlet:
    context-path: /associacao